Traduction de `advanced/lazy-loading.md`
vuejs-fr/vue-router pull request #10
Opened 2017-05-24 14:32 UTC by Kocal

2017-05-27 13:49 UTC, MachinisteWeb requested changes
Merci @Kocal. Voici ma review.

2017-05-27 13:49 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +# Les Routes chargeant à la volée
Je propose

# Les routes chargées à la volée

ou

# Le chargement à la volée

2017-05-27 13:49 UTC, Haeresis commented on docs/en/SUMMARY.md
> +  - [Le chargement à la volée](advanced/lazy-loading.md)
Que pense tu d'aligner nos titres avec le menu, quitte à les raccourcir ?

2017-05-27 13:49 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +Pendant la construction d'applications avec un « bundler », le paquet JavaScript peut devenir un peut lourd, et donc cela peut affecter le temps de chargement de page. Il serait plus efficace si l'on
> un empaqueteur (« bundler »)

> un peu

> et de ~~ne~~ les charger uniquement

2017-05-27 13:49 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +En combinant la [fonctionnalité de composant asynchrone](http://vuejs.org/guide/components.html#Async-Components) de Vue et la [fonctionnalité de séparation de code](https://webpack.js.org/guides/cod
Lien FR

> [fonctionnalité de composant asynchrone](https://fr.vuejs.org/v2/guide/components.html#Composants-asynchrones)

> webpack

avec une minuscule, je PR l'original

2017-05-27 13:49 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +  // require.ensure est une syntaxe spéciale de Webpack pour une séparation de code.
> `require.ensure`

avec tick et

> webpack 

sans majuscule

Je PR l'original

2017-05-27 13:49 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +### Grouper des composants dans le même morceau
on traduit `chunk` par fragment : 

> même fragment

J'ai ajouté l'info dans l'issue des trads now

2017-05-27 13:49 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +Webpack groupera tous les modules asynchrones avec le même nom de morceau, dans le même morceau asynchrone &mdash; cela signifie aussi que nous n'avons plus besoin de lister explicitement les dépenda
> webpack

> asynchrone. Cela signifie

2017-05-27 14:27 UTC, Kocal commented on docs/en/advanced/lazy-loading.md
> +# Les Routes chargeant à la volée
Oulah, je sais pas pourquoi j'ai écris « chargeant », peut-être la fatigue :stuck_out_tongue_closed_eyes: 

Je garde la 1ère proposition (tu remarqueras que le titre dans le `SUMMARY.md` est différent avec le titre du `api/lazy-loading.md`

2017-05-27 14:34 UTC, Kocal commented on docs/en/advanced/lazy-loading.md
> +Webpack groupera tous les modules asynchrones avec le même nom de morceau, dans le même morceau asynchrone &mdash; cela signifie aussi que nous n'avons plus besoin de lister explicitement les dépenda
Je laisse `Webpack` car il est au début de la phrase.

Est-ce que je modifie le `&mdash;` ?

2017-05-27 14:35 UTC, Kocal commented on docs/en/SUMMARY.md
> +  - [Le chargement à la volée](advanced/lazy-loading.md)
Ça marche !

2017-05-27 16:04 UTC, MachinisteWeb requested changes
Seconde review. Encore quelque petit trucs.

2017-05-27 16:04 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +Pendant la construction d'applications avec un empaqueteur (« bundler »), le paquet JavaScript peut devenir un peu lourd, et donc cela peut affecter le temps de chargement de page. Il serait plus eff
> de la page

p-e ?

2017-05-27 16:04 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +Tout ce dont nous avons à faire, c'est de définir les composants de notre route en tant que composants asynchrones :
> Tout ce que nous avons à faire

ou

> Tout ce dont nous devons nous soucier

:)

2017-05-27 16:04 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +Webpack groupera tous les modules asynchrones avec le même nom de morceau, dans le même morceau asynchrone. Cela signifie aussi que nous n'avons plus besoin de lister explicitement les dépendances po
> webpack sans majuscule, même en début de phrase http://webpack.github.io/docs/

2017-05-27 18:36 UTC, Kocal commented on docs/en/advanced/lazy-loading.md
> +Pendant la construction d'applications avec un empaqueteur (« bundler »), le paquet JavaScript peut devenir un peu lourd, et donc cela peut affecter le temps de chargement de page. Il serait plus eff
Oui c'est mieux avec le `la` !

2017-05-27 18:41 UTC, Kocal commented on docs/en/advanced/lazy-loading.md
> +Webpack groupera tous les modules asynchrones avec le même nom de morceau, dans le même morceau asynchrone. Cela signifie aussi que nous n'avons plus besoin de lister explicitement les dépendances po
Oh d'accord, étrange :hushed:

2017-05-27 18:41 UTC, Kocal commented
Modifié !

2017-05-29 06:59 UTC, MachinisteWeb requested changes
Deux points et bon pour moi !

2017-05-29 06:59 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +Pendant la construction d'applications avec un empaqueteur (« bundler »), le paquet JavaScript peut devenir un peu lourd, et donc cela peut affecter le temps de chargement de la page. Il serait plus
> chaque composant

2017-05-29 06:59 UTC, Haeresis commented on docs/en/advanced/lazy-loading.md
> +webpack groupera tous les modules asynchrones avec le même nom de morceau, dans le même morceau asynchrone. Cela signifie aussi que nous n'avons plus besoin de lister explicitement les dépendances po
> nom de fragment, dans le même fragment

2017-06-02 06:13 UTC, Haeresis commented
Deux points et bon pour moi ! @Kocal

2017-06-02 06:48 UTC, Kocal commented
Modifié

2017-06-02 06:54 UTC, MachinisteWeb approved these changes

2017-06-02 06:54 UTC, merged