Traduction de `advanced/data-fetching.md`
vuejs-fr/vue-router pull request #12
Opened 2017-05-27 05:22 UTC by Kocal

2017-05-27 12:53 UTC, MachinisteWeb requested changes
Plusieurs point de consistence.

Bon boulot !

Je sais pas si tu avais pris en compte notre discussion a ce niveau de traduction sur In-Component Guard pour « Composant de sécurisation »

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +- **Récupération de donnée avant la navigation** : récupère les données avant la navigation dans la fonction de garde d'entrée de la route, et effectue la navigation après que les données aient été r
Suite à notre discussion

> la fonction de sécurisation

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +Techniquement, les deux choix sont valides &mdash; cela dépend de l'expérience utilisateur que vous souhaitez apporter.
> valides. Cela

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +En utilisant cette approche, nous naviguons et faisons immédiatement le rendu du composant, et récupère les données via le hook `created` du composant. Cela nous donne l'opportunité d'afficher un éta
Conserver le nous / éviter les virgules en français devant les « et »

> du composant et récupérons

> pendant que

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +Assumons que nous ayons un composant `Post` qui a besoin de récupérer des données pour un post identifié par `$route.params.id` :
> pour un billet (c.f. billet de blog)

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +    // récupère les données lorsque la vue est créée et
> récupérer

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +    // on appelle encore la méthode si la route change
> appeler

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +      // remplacez getPost par votre fonction de récupération de données
> remplacer `getPost` par une fonction de récupération de données

(j'ouvre une PR à l'original pour les ticks)

2017-05-27 12:53 UTC, Haeresis commented on docs/en/advanced/data-fetching.md
> +Avec cette approche, nous récupérerons les données avant de naviguer vers la nouvelle route. Nous pouvons effectuer la récupération de données dans la fonction de garde `beforeRouteEnter` du composan
> la fonction de sécurisation

2017-05-27 13:45 UTC, Kocal commented
Il me semble avoir écrit traduit en `fonction de sécurisation` dans mes PR précédentes, mais j'ai toujours du mal à utiliser ce terme.
J'imagine plutôt des « gardes » avec lesquels tu pourrais interagir ou non dans les différents hooks de vue-router, un peu comme des middlewares dans Laravel :/ 

Pour l'instant je laisse les modifs à propos des `guard function` en suspens, en espérant qu'on relance un débat là-dessus avec plus de personnes !

(Après, ça peut aussi venir de vue-router qui a mal interprété `guard function` hehe)

2017-05-27 16:02 UTC, Haeresis commented
En ce qui concerne le terme tu peux toujours ouvrir une issue pour revenir rétroactivement sur le terme. Pour le moment, afin de ne pas bloquer le travail, je t'encourage à adopter  « sécurité / sécurisation » ici ou « garde » partout ailleurs mais de conserver une consistance.

En [holacratie](http://labdsurlholacracy.com/bande-dessinee-holacracy) l'idée c'est d'avancé pas à pas et de se dire que chaque tension peut être retraité à l'infinie sans bloquer le travail global de la Raison d'être de l'entreprise. Je pense qu'étant donnée que les issues et PR sont faisable à l'infinie, on peut revenir sur ce point plus tard. Sinon on peut toujours bloquer cette PR ici mais c'est dommage d'autant que tu as utilisé sécurisation partout ailleurs.

On peut également voir si sa passe la validation de l'équipe Vue Router car l'un des décideurs est français et il fait des relectures avant validation. Quand quelque chose lui paraît vraiment « trop » en général ça repars en discussion ici.

2017-05-27 18:33 UTC, Kocal commented
Bon très bien, je pars sur `fonction de sécurisation`, mais j'aimerai beaucoup qu'on lance un petit débat avec plusieurs membres du groupe !

Tu peux approuver les changements ~

2017-05-29 06:56 UTC, MachinisteWeb approved these changes

2017-05-29 08:49 UTC, merged