Traduction de `navigation.md`
vuejs-fr/vue-router pull request #16
Opened 2017-06-17 14:24 UTC by Haeresis

Et un fichier de plus. Je vais m'arrêter là pour aujourd'hui !

2017-06-17 19:47 UTC, Kocal requested changes
De 4, quelques petits trucs à corriger :)

2017-06-17 19:47 UTC, Kocal commented on docs/en/essentials/navigation.md
> +Pour naviguer à différentes URLs, utilisez `router.push`. Cette méthode ajoute une nouvelle entrée dans la pile de l'historique. Ainsi quand un utilisateur clique sur le bouton retour de son navigate
> naviguer vers une URL différente,

2017-06-17 19:47 UTC, Kocal commented on docs/en/essentials/navigation.md
> +Cette méthode est appelée en interne quand vous cliquez sur `<router-link>`. Aussi cliquer sur `<router-link :to="...">` est un équivalent à l'appel de `router.push(...)`.
>, donc cliquer sur `<router-link :to="...">` est équivalent à appeler `router.push(...)`

2017-06-18 11:08 UTC, Haeresis commented
Mercie @Kocal. Si c'est bon pour toi je merge.

2017-06-18 13:19 UTC, Kocal approved these changes

2017-06-18 13:19 UTC, Kocal commented
Bon également ici :)

2017-06-18 13:24 UTC, merged