Traduction de `named-routes.md`
vuejs-fr/vue-router pull request #18
Opened 2017-06-17 15:30 UTC by Haeresis

Les routes nommées sont là.

2017-06-17 19:27 UTC, Kocal requested changes
Et de 2 !

2017-06-17 19:27 UTC, Kocal commented on docs/fr/essentials/named-routes.md
> +Parfois il est plus pratique d'identifer une route avec un nom, tout particulièrement quand on souhaite attacher cette route ou exécuter des actions de navigation. Vous pouvez donner à une route un n
> donner un nom à une route

2017-06-18 10:03 UTC, Haeresis commented
Exact j'ai pas mis à jour le fichier depuis le bon dossier. Je rectifie ça en même temps.

2017-06-18 11:12 UTC, Haeresis commented
J'ai ajouté tes modifs et délacer dans le dossier EN. Si c'est bon pour toi @Kocal, je merge.

2017-06-18 13:19 UTC, Kocal approved these changes

2017-06-18 13:19 UTC, Kocal commented
Ok pour moi !

2017-06-18 13:23 UTC, merged