Traduction de `navigation-guards.md`
vuejs-fr/vue-router pull request #24
Opened 2017-07-13 15:38 UTC by Haeresis

Et voilà notre dernière page !

2017-07-14 07:52 UTC, Haeresis commented
Fini par celle ci @Kocal car je change la terminologie de « Sécurisation » par « Interception » dans plusieurs fichiers.

2017-07-15 13:45 UTC, Kocal requested changes

2017-07-15 13:45 UTC, Kocal commented on docs/en/advanced/navigation-guards.md
> +# Interceptions de navigation
> Intercepteurs de navigation

2017-07-15 13:45 UTC, Kocal commented on docs/en/SUMMARY.md
> +  - [Interceptions de navigation](advanced/navigation-guards.md)
> Intercepteurs de navigation

2017-07-15 13:45 UTC, Kocal commented on docs/en/api/router-instance.md
> +  Ajout des interceptions globales de navigation. Voir les [Interceptions de navigation](../advanced/navigation-guards.md).
> des intercepteurs globaux de navigation

> Voir les [Intercepteurs de navigation]

2017-07-15 14:44 UTC, Haeresis commented
Si bon pour toi, on merge !

2017-07-15 17:18 UTC, Kocal approved these changes

2017-07-15 17:19 UTC, Kocal commented
Ok pour moi. ^^

2017-07-16 09:22 UTC, merged