Traduction de `installation.md`
vuejs-fr/vue-router pull request #3
Opened 2017-05-05 20:09 UTC by Kocal

Une idée pour traduire efficacement `Dev Build` ?

2017-05-06 06:19 UTC, Haeresis commented
Dans de nombreux cas il est très difficile de traduire build car il peut signifier énormément de chose. C'est d'ailleurs pour cela que même en français on dit sourvent *build*.

On l'a laissé dans les mots que l'on peut ne pas traduire ce qui donne : 

Ex : Build Dev => « Source pour compilation » mais éloigné des termes d'origine. 

On peut donc laisser « Build de développement ».

2017-05-06 06:21 UTC, Haeresis commented
Dans de nombreux cas il est très difficile de traduire build car il peut signifier énormément de chose. C'est d'ailleurs pour cela que même en français on dit souvent *build*.

On l'a laissé dans les mots que l'on peut ne pas traduire ce qui donne : 

Par exemple pour ce contexte ci on peut mettre : 

Build Dev => « compilation de développement » 

On peut donc laisser « Build de développement ».

2017-05-08 07:45 UTC, MachinisteWeb requested changes
Bien joué @Kocal 

Rien à redire non plus mais on s'aperçoit que c'est une traduction quasiement identique avec Vuex et qu'il y a des écarts de traduction. Mes propositions vont dans le sens de tenter de conserver une cohérence entre les deux traductions même si fondamentalement tout roule !

2017-05-08 07:45 UTC, Haeresis commented on docs/en/installation.md
> +[Unpkg.com](https://unpkg.com) met à disposition des liens CDN basés sur NPM. Le lien ci-dessus pointera toujours vers la dernière release publiée sur NPM. Vous pouvez également spécifier une certain
Aligner cette traduction avec l'installation de Vuex (notamment pour version/tag) qui a été décomposé, je trouve ça plus courent en français : 

> fournit des liens CDN basés sur NPM. Le lien ci-dessus pointera toujours vers la dernière release sur NPM. Vous pouvez aussi utiliser un tag ou une version spécifique via une URL comme

2017-05-08 07:45 UTC, Haeresis commented on docs/en/installation.md
> +Inclure `vue-router` après Vue, et il s'installera automatiquement de lui-même :
> Aligner avec vuex

2017-05-08 07:45 UTC, Haeresis commented on docs/en/installation.md
> +Vous n'avez pas besoin de faire cela lors de l'utilisation des tags `<script>`.
Pour aligner Vuex et Vue Router

> Vous n'avez pas besoin de faire cela lors de l'utilisation des balises de script globales (`<script>`).

2017-05-08 07:45 UTC, Haeresis commented on docs/en/installation.md
> +Vous aurez besoin de cloner directement `vue-router` depuis GitHub et le construire vous-même si vous souhaitez utiliser la dernière dev build.
Je propose pour aligner Vuex et Vue Roteur

> Vous aurez besoin de cloner directement `vue-router` depuis GitHub et le compiler vous-même si vous souhaitez utiliser le dernier build de développement.

2017-05-08 07:45 UTC, Haeresis commented on docs/en/installation.md
> +Inclure `vue-router` après Vue, et il s'installera automatiquement de lui-même :
Je propose celle de Vuex qui est moins littérale mais plus fluide (pas de , pas d’auto référence)

> Incluez `vuex` après Vue et l'installation sera automatique :

2017-05-08 15:26 UTC, Kocal commented on docs/en/installation.md
> +[Unpkg.com](https://unpkg.com) met à disposition des liens CDN basés sur NPM. Le lien ci-dessus pointera toujours vers la dernière release publiée sur NPM. Vous pouvez également spécifier une certain
Fixé dans 1d922bd.

2017-05-08 15:26 UTC, Kocal commented on docs/en/installation.md
> +Inclure `vue-router` après Vue, et il s'installera automatiquement de lui-même :
Fixé dans 1d922bd.

2017-05-08 15:26 UTC, Kocal commented on docs/en/installation.md
> +Vous n'avez pas besoin de faire cela lors de l'utilisation des tags `<script>`.
Fixé dans 1d922bd.

2017-05-08 15:26 UTC, Kocal commented on docs/en/installation.md
> +Vous aurez besoin de cloner directement `vue-router` depuis GitHub et le construire vous-même si vous souhaitez utiliser la dernière dev build.
Fixé dans 1d922bd.

2017-05-08 15:27 UTC, Kocal commented
C'est bon, je viens d'apporter les modifs pour s'aligner avec le fichier `installation.md` de Vuex (1d922bd).
Tu peux merger.

2017-05-09 06:01 UTC, MachinisteWeb approved these changes

2017-05-09 06:02 UTC, merged