Traduction de `essentials/getting-started.md`
vuejs-fr/vue-router pull request #4
Opened 2017-05-08 16:34 UTC by Kocal

2017-05-10 10:16 UTC, MachinisteWeb requested changes
Merci pour la traduction !

Divers point à corriger et surement un autre « conflit » à résoudre avant de pouvoir valider la pull request

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +> Tous les exemples utiliseront la version standalone de Vue pour rendre l'analyse de template possible. Plus de détails [ici](https://fr.vuejs.org/guide/installation.html#Runtime-Compiler-vs-Runtime
> la version complète

La Version « standalone » a été modifié en la version « full » (Compiler + Runtime vs Runtime-only)

J'ai fait une PR dans ce sens pour la version EN, elle est passé. Il faut que tu mettes à jour ta branche vis à vis de `vuejs-fr/vue-router:working` et que tu résolves le confilt en concervant le terme « complète » dans ta traduction.

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +    <!-- spécifiez le lien en le passant à la propriété `to` -->
> spécifiez le lien en le passant à la prop `to`

C'est un terme propre à Vue que nous concervons donc tel quel.

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +// 0. Si vous utilisez un système de module (e.g. via vue-cli), il faut importer Vue et VueRouter et ensuite appeler Vue.use(VueRouter).
> (ex : via vue-cli)

On traduit tout les e.g. par ex même si ça existe tout de même en français car c'est moins rependu que « ex »

On ferra une PR global pour changer tous les « ex » par « par ex. » plus tard (déjà discuté dans une PR)

> `Vue.use(VueRouter)`. (entre `)

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +// 1. Définir des composants.
> Définissez les composants de route

Pour être cohérant avec ta traduction plus haute. Ou inversement plus haut tu passe les « ez » à l'impératif

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +// 2. Définir des routes.
> Définissez des routes

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +// Chaque route doit corresponde à un composant. Le "composant" peut
> correspondre

> « composant »

2017-05-10 10:16 UTC, MachinisteWeb commented on docs/en/essentials/getting-started.md
> +// 3. Créer l'instance du routeur et passer l'option `routes`.
> Créez

> Passez

2017-05-10 10:16 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +  routes // raccourci pour routes: routes
> même si pas dans original, ajoute `routes: routes` (entre `)

2017-05-10 10:16 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +// soit être un véritable composant créé via Vue.extend(), ou juste un
> Même si pas das original ajoute `Vue.extend()` (entre `)

2017-05-10 10:16 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +    <!-- <router-link> sera rendu en tag `<a>` par défaut -->
> `router-link` (entre `)

2017-05-10 10:16 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +// 5. Créer et monter l'instance de Vue.
Créez et montez

2017-05-10 10:16 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +Notez qu'un `<router-link>` obtiendra automatiquement la classe `router-link-active` lorsque sa route cible correspond avec la route actuelle. Vous pouvez en apprendre plus à propos de cela dans sa [
garder `.router-link-active` avec le point ou écrire la classe router-link-active sans les ` (je préfère rester fidèle à l'original).

2017-05-11 08:52 UTC, Kocal commented on docs/en/essentials/getting-started.md
> +Notez qu'un `<router-link>` obtiendra automatiquement la classe `router-link-active` lorsque sa route cible correspond avec la route actuelle. Vous pouvez en apprendre plus à propos de cela dans sa [
Je comprend pourquoi tu veux rester fidèle à l'original, mais ça m'embête un peu de faire un pléonasme ^^

`.router-link-active`, on sait que c'est une classe, écrire « la classe `.router-link-active` » m'embête un peu, mais je vais apporter les modifications nécessaires.

2017-05-11 09:04 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +Notez qu'un `<router-link>` obtiendra automatiquement la classe `router-link-active` lorsque sa route cible correspond avec la route actuelle. Vous pouvez en apprendre plus à propos de cela dans sa [
Compris pour le pléonasme. Pour essayer d'effacer ta gène, essaye de voir si elle y est toujours là dedans :

> Utiliser la balise `<a>` pour faire des liens. Avec la classe `.btn` celui-ci ressemblera a un bouton mais attentions à l'attribut `target="_blank"` qui ouvrira le lien dans un nouvel onglet !

ou

>Utiliser la balise *a* pour faire des liens. Avec la classe *btn* celui-ci ressemblera a un bouton mais attentions à l'attribut *target* en mode *blank* qui ouvrira le lien dans un nouvel onglet !

En fait le point ici c'est que si tu mets les ` tu es censé y écrire un pend de code. Et comme `router-link-active` n'est pas un pend de code « compréhensible » il est mieux avec un point (ou alors comme ça `class="router-link-active"` mais la on s'éloigne vraiment de l'original et ta gène ressenti du point de vu pléonasme est à la fête !

2017-05-11 09:08 UTC, MachinisteWeb requested changes
Petit enchaînement de mot en conflit :)

2017-05-11 09:08 UTC, Haeresis commented on docs/en/essentials/getting-started.md
> +Notez qu'un `<router-link>` obtiendra automatiquement la classe `.router-link-active` lorsque sa route cible correspond avec la route actuelle. Vous pouvez en apprendre plus à propos de cela dans sa
> correspond à la route

2017-05-12 07:15 UTC, Haeresis commented
Je refais une lecture

2017-05-18 11:48 UTC, MachinisteWeb approved these changes

2017-05-18 11:49 UTC, merged