Traduction de `api/component-injections.md` et `api/router-instance.md`
vuejs-fr/vue-router pull request #5
Opened 2017-05-23 16:43 UTC by Kocal

2017-05-27 15:56 UTC, MachinisteWeb requested changes
Voici mes retours.

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +# L'Instance Routeur
> L'instance du routeur

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +  La route actuelle représentée en tant qu'un [Objet Route](route-object.md).
>qu'un [objet route]

Si on affiche clairement que c'est un titre, on met une majuscule. Si on cache le titre dans la phrase, on en met pas. C'est arbitraire bien sur, mais c'est la règle que j'utilise dans mes traductions. Tu peux la suivre pour la consistance si tu le souhaites.

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +  Retourne un `Array` des composants (définition/constructeur et non les instances) correspondant à la `location` passée en paramètre, ou alors de la route actuelle. Cette fonction est principalement
> Retourne un tableau de composants

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +  Inverse la résolution d'URL. La `location` doit avoir la même forme qu'utilisée dans `<router-link>`, retourne un `Object` avec les propriétés suivantes :
> un objet avec les propriétés suivantes

objet et tableau son parfaitement francisé dans le domaine du JavaScript

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +  Permet d'ajouter dynamiquement des routes au routeur. L'argument doit être un `Array` utilisant le même format de configuration que l'option `routes` du constructeur.
> tableau utilisant

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +  Cette méthode met en file d'attente une fonction de rappel qui sera appelée lorsque le routeur aura complété la navigation initiale, ce qui signifie qu'il a résolu tous les hooks d'entrée asynchron
> hooks d'entrées

2017-05-27 15:56 UTC, Haeresis commented on docs/en/api/router-instance.md
> +  Enregistre une fonction de rappel qui sera appelée lorsqu'une erreur sera capturée pendant la navigation à une route. Notez que pour qu'une erreur soit appelée, cela doit correspondre à l'un des sc
> vers une route

2017-05-27 19:02 UTC, Kocal commented
Modifications apportées !

2017-05-29 07:10 UTC, MachinisteWeb approved these changes
Ok pour moi !

2017-05-29 07:11 UTC, Haeresis commented
Conflit à résoudre à priori :D

2017-05-29 07:12 UTC, merged

2017-05-29 08:48 UTC, Kocal commented
Oui c'est parce que j'étais parti de la branche working pour chaque PR que j'ai faite, donc forcément, au bout d'un moment ça commençait à être galère dans le `SUMMARY.md` ^^