Traduction de `api/options.md`
vuejs-fr/vue-router pull request #6
Opened 2017-05-23 18:57 UTC by Kocal

2017-05-27 15:37 UTC, MachinisteWeb requested changes
Autre review

2017-05-27 15:37 UTC, Haeresis commented on docs/en/api/options.md
> +# Options de Construction du Routeur
> de construction du routeur

2017-05-27 15:37 UTC, Haeresis commented on docs/en/api/options.md
> +- défaut : `"hash" (dans le navigateur) | "abstract" (dans Node.js)`
> en Node.js

2017-05-27 15:37 UTC, Haeresis commented on docs/en/api/options.md
> +  - `history` : nécessite l'API History d'HTML 5 et la configuration du serveur. Voir [Mode d'Historique HTML5](../essentials/history-mode.md).
> Mode historique de HTML5

2017-05-27 15:37 UTC, Haeresis commented on docs/en/api/options.md
> +  L'URL de base de l'application. Par exemple, si l'entière application monopage est distribuée sous `/app/`, alors `base` doit utiliser la valeur `"/app/"`.
> si l'application monopage entière

2017-05-27 15:37 UTC, Haeresis commented on docs/en/api/options.md
> +  Pour plus de détails, voir [Comportement du Scroll](../advanced/scroll-behavior.md).
> Comportement du défilement

2017-05-27 15:37 UTC, Haeresis commented on docs/en/api/options.md
> +  Permet de spécifier des fonctions customisées pour parser / stringifier la requête. Surcharge les fonctions par défaut.
> Permet de spécifier des fonctions personnalisées pour formater en fonctions ou en chaîne de caractère la requête.

2017-05-27 18:51 UTC, Kocal commented on docs/en/api/options.md
> +  Permet de spécifier des fonctions customisées pour parser / stringifier la requête. Surcharge les fonctions par défaut.
> en fonction d'un objet

?

2017-05-27 18:57 UTC, Kocal commented
Modifications apportées

2017-05-29 07:08 UTC, MachinisteWeb approved these changes
Top !

2017-05-29 07:08 UTC, merged