Traduction de `api/router-link.md`
vuejs-fr/vue-router pull request #9
Opened 2017-05-24 05:49 UTC by Kocal

2017-05-27 14:49 UTC, MachinisteWeb requested changes
Review pour celle là

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +- Dans le mode historique HTML5, `router-link` interceptera l'événement du clic, comme ça le navigateur n'essaiera pas de rafraîchir la page.
> évènement

les deux sont valide mais on garde la réforme de 1990 (ou 1991) je sais plus :D

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +   Désigne la route cible du lien. Lorsqu'il est cliqué, la valeur de la prop `to` va être passé de manière interne à `router.push`, donc la valeur peut soit être une chaîne de caractères, ou alors u
> être passée

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  <!-- expression JavaScript en utilisant v-bind -->
`v-bind`

Je notifie l'original

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  <!-- Omettre v-bind est ok, tout comme autre prop -->
`v-bind` avec tick

Je PR original

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  <!-- Omettre v-bind est ok, tout comme autre prop -->
> une autre prop

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  <!-- avec une requête, résulte en /register?plan=private -->
`/register?plan=private` avec tick

Je PR

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  Parfois, on veut que `<router-link>` soit rendu avec un tag différent, ex : `<li>`. On peut alors utiliser la prop `tag` pour modifier le tag qui sera rendu, et il écoutera toujours aux événements
> modifier la balise

> sera rendue

> et elle écoutera toujours les évènements de clic

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  Une conséquence de cela est que `<router-link to="/">` sera actif pour toutes les routes ! Pour forcer le lien dans un "mode correspondance exacte", utilisez la prop `exact`.
> « mode correspondance exacte »

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  <!-- ce lien sera uniquement actif à / -->
à `/`

PR original

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +  Spécifie les événement(s) que peuvent lancer la navigation de lien.
> les évènement(s) qui peu(ven)t lancer

2017-05-27 14:49 UTC, Haeresis commented on docs/en/api/router-link.md
> +Parfois, on voudrait que la classe active soit appliquer à un élément extérieur au lieu de l'élément `<a>` lui-même, dans ce cas, vous pouvez faire le rendu de cet élément extérieur en utilisant `<ro
> soit appliquée

2017-05-27 15:03 UTC, Kocal commented
Corrigé ~

2017-05-27 16:07 UTC, MachinisteWeb requested changes
Seconde relecture

2017-05-27 16:07 UTC, Haeresis commented on docs/en/api/router-link.md
> +`<router-link>` est le composant pour activer la navigation utilisateur dans une application où le routeur est activé. La localisation cible est spécifiée grâce à la prop `to`. Il est rendu en tant q
> en tant que balise

2017-05-27 16:07 UTC, Haeresis commented on docs/en/api/router-link.md
> +`<router-link>` est préféré par rapport au `<a href="...">` hard-codé pour les raisons suivantes :
> en dur pour les raisons

ou 

> en dur dans le code pour les raisons

2017-05-27 18:47 UTC, Kocal commented
Modification apportée, tu peux approuver si ça te va

2017-05-29 07:06 UTC, MachinisteWeb requested changes
Encore une relecture. Après ça pour moi c'est bon!

2017-05-29 07:06 UTC, Haeresis commented on docs/en/api/router-link.md
> +  Parfois, on veut que `<router-link>` soit rendu avec un tag différent, ex : `<li>`. On peut alors utiliser la prop `tag` pour modifier la balise qui sera rendue, et elle écoutera toujours les évène
> une balise différente

2017-06-02 06:14 UTC, Haeresis commented
Après ça pour moi c'est bon @Kocal !

2017-06-02 06:45 UTC, Kocal commented
Oups, j'avais mis de côté la traduction à cause d'un projet à l'IUT, c'est fixé ~

2017-06-02 06:54 UTC, MachinisteWeb approved these changes

2017-06-02 06:54 UTC, merged